version: '3'
services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: sample_app_development
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - '3306:3306'
        volumes:
            - mysql_volume:/var/lib/mysql
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        stdin_open: true
        tty: true  # コンテナを起動させ続ける
        depends_on:
            - db
        volumes:
            - .:/app
            - gem-data:/usr/local/bundle

volumes:
    mysql_volume:
    gem-data: